### ISSUE TITLE
Nested projection normalization results in ambiguity

### ISSUE THREAD

**Issue by compiler-errors** [compiler-errors/next-solver-hir-issues#13]
```rust
fn needs_iter(_: impl Iterator<Item = i32>) {}

fn main() {
    needs_iter(IntoIterator::into_iter([0i32; 32]))
}
```

```
error[E0284]: type annotations needed: cannot satisfy `<<[i32; 32] as IntoIterator>::IntoIter as Iterator>::Item == i32`
 --> <source>:4:16
  |
4 |     needs_iter(IntoIterator::into_iter([0i32; 32]))
  |     ---------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot satisfy `<<[i32; 32] as IntoIterator>::IntoIter as Iterator>::Item == i32`
  |     |
  |     required by a bound introduced by this call
  |
note: required by a bound in `needs_iter`
 --> <source>:1:32
  |
1 | fn needs_iter(_: impl Iterator<Item = i32>) {}
  |                                ^^^^^^^^^^ required by this bound in `needs_iter`
```

This may be due to us assembling two candidates -- one via the alias bound for `IntoIter` and one via the normalized self type `<[i32; 32] as IntoIterator>::IntoIter` which is `std::array::IntoIter<i32, 32>`...

I'm surprised we're not combining these because they should have the same constraints -- none at all.

**Comment by compiler-errors** [comment]
Marking this as a "fundamental" issue because we're going to have to hack around it at the solver level, possibly by not preferring alias bounds over impl bounds (or perhaps getting rid of alias bounds altogether)

**Comment by lcnr** [comment]
> I'm surprised we're not combining these because they should have the same constraints -- none at all.

i don't think we combine candidates yet until https://github.com/rust-lang/rust/pull/109724 so i think at least this specific case should be fixed with that?

**Comment by compiler-errors** [comment]
oh you're right, duh. well glad it's fixed by that.

**Comment by compiler-errors** [comment]
@lcnr this doesn't seem to be fixed by your pr

**Comment by lcnr** [comment]
inside of the `normalizes-to` rhs infer hack:

```rust
  Candidate { source: Impl(DefId(2:3663 ~ core[523c]::array::iter::{impl#2})), result: Canonical { value: Response { certainty: Yes, var_values: CanonicalVarValues { var_values: [i32] }, external_constraints: ExternalConstraints(Interned(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [] }, PrivateZst)) }, max_universe: U0, variables: [] } },
  Candidate { source: AliasBound, result: Canonical { value: Response { certainty: Yes, var_values: CanonicalVarValues { var_values: [<[i32; 32] as std::iter::IntoIterator>::Item] }, external_constraints: ExternalConstraints(Interned(ExternalConstraintsData { region_constraints: QueryRegionConstraints { outlives: [], member_constraints: [] }, opaque_types: [] }, PrivateZst)) }, max_universe: U0, variables: [] } }]
```
normalizing to either `i32` or `<[i32; 32] as std::iter::IntoIterator>::Item` :sweat_smile: have a few different ideas here, can chat about them in sync :grin:

**Comment by compiler-errors** [comment]
Moving to rust-lang/trait-system-refactor-initiative#4
